### ISSUE TITLE
Unhandled Exception as a result of cache flushing

### ISSUE THREAD

**Issue by bk5115545** [trakos/CFAN#2]
**CFAN Version:** 
0.0.2-0

**Operating System:** 
Windows 10 x64 Professional

**The issue you are experiencing:** 
System.IO.FileNotFoundException resulting in app crash

**How to recreate this issue:** 
1. Install any mod.
2. Remove that mod
3. Settings->CFAN Settings->Clear cache
4. Reinstall that mod

**CFAN error codes (if applicable):** 
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

*************\* Exception Text **************
System.IO.FileNotFoundException: Could not find file 'C:\Users\Bryan Koch\Desktop\Factorio_0.12.29.stable\CFAN\downloads\30D497D9-additionaloilrefineries_1.0.0'.
File name: 'C:\Users\Bryan Koch\Desktop\Factorio_0.12.30.alpha\CFAN\downloads\30D497D9-additionaloilrefineries_1.0.0'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at ICSharpCode.SharpZipLib.Zip.ZipFile..ctor(String name)
   at CKAN.NetFileCache.GetCachedZip(Uri url, Boolean test_data)
   at CKAN.NetFileCache.IsCachedZip(Uri url)
   at CKAN.ModuleInstaller.InstallList(ICollection`1 modules, RelationshipResolverOptions options, IDownloader downloader)
   at CKAN.Main.WasSuccessful(Action action)
   at CKAN.Main.InstallList(HashSet`1 toInstall, RelationshipResolverOptions options, IDownloader downloader)
   at CKAN.Main.InstallMods(Object sender, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

Additional Info:
There is a FileSystemWatcher at https://github.com/trakos/CFAN/blob/master/Core/Net/NetFileCache.cs#L24 that appears to be correctly flushing the cache when the cache is changed however it doesn't appear that the TxFileManager at https://github.com/trakos/CFAN/blob/master/Core/Net/Repo.cs#L23 is correctly implemented.

https://github.com/trakos/CFAN/blob/master/Core/Net/Repo.cs#L237 should probably be changed to something like below for the signaling to work properly (as per https://github.com/rsevil/Transactions).

```
using (TransactionScope scope1 = new TransactionScope())
{
    file_transaction.Delete(repo_file);
    scope1.Complete();
}
```

Oh and about me setting up my build environment; I probably just don't have the correct C# compiler version.  I use some pretty old versions of C# for work but the latest C++.

**Comment by bk5115545** [comment]
More info:
https://github.com/trakos/CFAN/blob/master/Core/Net/NetFileCache.cs#L274
should probably be the below as well.

```
using (TransactionScope scope1 = new TransactionScope())
{
    tx_file.Delete(file);
    scope1.Complete();
}
```

**Comment by trakos** [comment]
Hey, I think FileSystemWatcher does not pick up changes as it should. I referenced this in upstream, as I could recreate the issue with their version as well: https://github.com/KSP-CKAN/CKAN/issues/1658

I've fixed by re-checking whether file exists, but I'll backport their fix if they will have better way to handle it.
